[package]
name = "aci-export"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aci-export"
path = "src/main.rs"
doc = false

[workspace]
members = ["db"]

[workspace.dependencies]
sqlx = { version = "0", features = ["runtime-tokio-rustls", "mysql", "chrono"] }

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
config = { version = "0", default-features = false, features = ["toml"] }
chrono = { version = "*", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0"
tokio = { version = "1", features = ["full"] }
csv = "1"
mailchimp-api = { git = "https://github.com/oxidecomputer/third-party-api-clients.git" }
db = { package = "aci-db", path = "db" }
sqlx = { workspace = true }
